### ISSUE TITLE
编写一个工具，用于检测文件/目录风格

### ISSUE THREAD

**Issue by axetroy** [axetroy/todo#130]
### 初衷/目标

在实际的项目中，有一些喜欢下划线风格 `aaa_bbb`, 有一些喜欢 `aaaBbb`

如果谁都可以这样乱来，最后项目很容易变成屎山

在这里，我就写一个工具，用于检测这些文件风格

暂时命名为 `fslint`

### TODO类型

- [ ] 类库
- [ ] 框架
- [ ] 服务
- [x] 命令行工具

### 预计时间

- [ ] 一天
- [x] 一周
- [ ] 两周
- [ ] 一月
- [ ] 更久

### 相关链接

[https://github.com/axetroy/fslint](https://github.com/axetroy/fslint)

**Comment by info-ruc** [comment]
good
