### ISSUE TITLE
完成微信小程序版的CNode社区开发

### ISSUE THREAD

**Issue by axetroy** [axetroy/todo#26]
很忙, 又加上最近很累, 下班了就想躺着, 实在没空搞. 

先记着, 时间就像x沟, 挤一挤还是有的

https://github.com/axetroy/wxapp-cnode

### 搁置

因为微信小程序官方提供的组件，对于HTML的渲染，还有一些问题

**Comment by alsotang** [comment]
> 对于HTML的渲染，还有一些问题
markdown 的问题是吧？
