### ISSUE TITLE
创建一个错误代码，错误信息平台

### ISSUE THREAD

**Issue by axetroy** [axetroy/todo#46]
### 初衷/目标

因为在日常开发中，需要抛出各种错误代码和错误信息。在多人开发中，就涉及到重复的问题。如果有效的避免重复的状态码，如何在错误信息模板附带变量，如果进行i18n的翻译。如何运用到多个平台，多语言。

所以想着写一个服务，就专门处理这一块的需求。

要满足以下功能: 
1. 各账号新增的错误代码自带命名空间，保证错误代码的唯一性
2. 错误代码的模板支持多语言
3. 选择各个错误代码模板，然后导出成json/yaml文件
4. 选择各个错误代码模板，然后生成对应语言的文件，例如Javascript/Go, 主要是为了方便ide的提示。

初选方案: 
前端页面显示用angular@4+
后端用nodejs

### TODO类型

- [x] 类库
- [ ] 框架
- [ ] 服务
- [ ] 命令行工具

### 预计时间

- [ ] 一天
- [x] 一周
- [ ] 两周
- [ ] 一月
- [ ] 更久

### 相关链接

[https://github.com/axetroy/todo](https://github.com/axetroy/todo)

**Comment by axetroy** [comment]
@WindomZ 
觉得如何

**Comment by WindomZ** [comment]
@axetroy 不知道我理解是不是你说的:
1. 一个统一的错误代码模板，json/yaml文件
1. 多语言的模块实现，支持自带命名空间，支持i18n
1. 实现一套工具集，基于模板生成多语言代码模块
