### ISSUE TITLE
写一篇Thrift的教程

### ISSUE THREAD

**Issue by axetroy** [axetroy/todo#72]
### 初衷/目标

记录下, 分享出来, 也怕以后忘记了

### TODO类型

- [x] 类库
- [ ] 框架
- [ ] 服务
- [ ] 命令行工具

### 预计时间

- [ ] 一天
- [x] 一周
- [ ] 两周
- [ ] 一月
- [ ] 更久

### 相关链接

[https://github.com/axetroy/todo](https://github.com/axetroy/todo)

**Comment by alsotang** [comment]
卧槽，17年的issue还不关啊。这东西现在还火吗？我目前接触到的都是pb

**Comment by axetroy** [comment]
以前写 RPC 的时候，能找到的最好的 RPC 框架

但是现在也基本用不到了，所以也没打算写了

留下一个以前写的 demo 好了

https://gist.github.com/axetroy/c2b3d2f47472078ca7cff0712fd4036a
