### ISSUE TITLE
实现一个 mini 版 react

### ISSUE THREAD

**Issue by huyansheng3** [axetroy/todo#81]
### 初衷/目标

为了对 react 的底层有更加深入的理解！

### TODO类型

- [x] 类库
- [ ] 框架
- [ ] 服务
- [ ] 命令行工具

### 预计时间

- [ ] 一天
- [ ] 一周
- [x] 两周
- [ ] 一月
- [ ] 更久

### 相关链接

[https://github.com/axetroy/todo](https://github.com/axetroy/todo)

**Comment by huyansheng3** [comment]
囧了

**Comment by axetroy** [comment]
@huyansheng3 
加油，写好了@我
