### ISSUE TITLE
写个babel插件，转换成性能更高的代码

### ISSUE THREAD

**Issue by axetroy** [axetroy/todo#94]
### 初衷/目标

优化内容包括

- [ ] 尾调用优化
- [ ] switch-case优化成obj function
- [ ] 大量if-else优化成switch
- [ ] 优化简单的三元表达式
- [ ] Typeof 优化
...

参考:

http://jsben.ch/qTUpg

### TODO类型

- [x] 类库
- [ ] 框架
- [ ] 服务
- [ ] 命令行工具

### 预计时间

- [ ] 一天
- [x] 一周
- [ ] 两周
- [ ] 一月
- [ ] 更久

### 相关链接

[https://github.com/axetroy/todo](https://github.com/axetroy/todo)

**Comment by alsotang** [comment]
前段时间有跟一个v8的人面谈，聊到过类似的插件。 https://twitter.com/hashseed
对于 v8 而言，很多结果等价的写法，由于v8处理的不同，性能有可能很大差异。
我建议那哥们给个v8官方的优化写法，这样就可以有人开发对应的eslint插件，当发现特定的低效模式出现时，给予提醒。
不过当时我们的结论是，v8的性能差异随版本而不同，总体还是不停在进步的。现在的优化很可能在下一个版本过时。写js代码还是关注可读性好了。

**Comment by axetroy** [comment]
@alsotang 

最近在贡献 `Deno` 项目，又有了新的感悟。

**不要为了那定点的性能优化而减少了代码可读性**

以前是想做来着，可是详细，编译器在不断的提升，一代版本一代神的，是在没必要

**Comment by alsotang** [comment]
是的，一代版本一代神
